// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

import (
	"github.com/google/wire"
	"io"
	"os"
)

// Injectors from injector.go:

func InitializedService() *SimpleService {
	simpleRepository := NewSimpleRepository()
	simpleService := NewSimpleService(simpleRepository)
	return simpleService
}

func InitializedError(isError bool) (*ErrorService, error) {
	errorRepository := NewErrorRepository(isError)
	errorService, err := NewErrorService(errorRepository)
	if err != nil {
		return nil, err
	}
	return errorService, nil
}

func InitializedMultiple() *DatabaseRepository {
	databaseMySQL := NewDatabaseMySQL()
	databaseMongoDB := NewDatabaseMongoDB()
	databaseRepository := NewDatabaseRepository(databaseMySQL, databaseMongoDB)
	return databaseRepository
}

func InitializedProviderSet() *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository)
	barRespository := NewBarRepository()
	barService := NewBarService(barRespository)
	fooBarService := NewFooBarService(fooService, barService)
	return fooBarService
}

func InitializedHelloService() *HelloService {
	sayHelloImpl := NewSayHelloImpl()
	helloService := NewHelloService(sayHelloImpl)
	return helloService
}

func InitializedStructProvider() *Fibonaci {
	fii := NewFii()
	boo := NewBoo()
	naci := NewNaci()
	fibonaci := &Fibonaci{
		Fii:  fii,
		Boo:  boo,
		Naci: naci,
	}
	return fibonaci
}

func InitializedFooBarUsingValue() *FooBar {
	foo := _wireFooValue
	bar := _wireBarValue
	fooBar := &FooBar{
		Foo: foo,
		Bar: bar,
	}
	return fooBar
}

var (
	_wireFooValue = fooValue
	_wireBarValue = barValue
)

func InitializedReader() io.Reader {
	reader := _wireFileValue
	return reader
}

var (
	_wireFileValue = os.Stdin
)

func InitializedConfiguration() *Configuration {
	application := NewApplication()
	configuration := application.Configuration
	return configuration
}

func InitializedConnection(name string) (*Connection, func()) {
	file, cleanup := NewFile(name)
	connection, cleanup2 := NewConnection(file)
	return connection, func() {
		cleanup2()
		cleanup()
	}
}

// injector.go:

var fooSet = wire.NewSet(NewFooRepository, NewFooService)

var barSet = wire.NewSet(NewBarRepository, NewBarService)

var helloSet = wire.NewSet(
	NewSayHelloImpl, wire.Bind(new(SayHello), new(*SayHelloImpl)),
)

var FibonaciSet = wire.NewSet(
	NewFii,
	NewBoo,
	NewNaci,
)

var fooValue = &Foo{}

var barValue = &Bar{}
